[package]
name = "emilybase-commit-model"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
emilybase-catalog = { path = "../catalog" }
emilybase-database = { path = "../database" }
emilybase-index = { path = "../index" }
emilybase-commit-format = { path = "../commit-format" }
sha2 = "0.10"
thiserror = "2"

[dev-dependencies]
proptest = "1"

[lints]
workspace = true
