use super::*;
use proptest::prelude::*;
use std::sync::Barrier;
use zeroize::Zeroize;

const SALT: &[u8; 16] = b"0123456789abcdef";

fn unhex(text: &str) -> [u8; 32] {
    assert_eq!(text.len(), 64);
    std::array::from_fn(|i| u8::from_str_radix(&text[i * 2..i * 2 + 2], 16).unwrap())
}

#[test]
fn exact_password_bytes_match_independent_c_argon2_vectors() {
    // Generated by argon2-cffi 25.1.0's C implementation with explicit costs.
    // These values are synthetic; they are not copied from this implementation.
    let pool = PasswordPool::new(1).unwrap();
    for (password, expected) in [
        (
            b"synthetic-password".to_vec(),
            "a4ae807f135c26201d1689dd0d26d93d04e28a91bf16dd1f3381535303db8656",
        ),
        (
            "синтетический\0пароль".as_bytes().to_vec(),
            "798f9db2e920dc9a7b72ab6fd69a2e3bc0794604becbb21b48004224b88a3ae8",
        ),
        (
            vec![b'x'; MAX_PASSWORD_BYTES],
            "7ea5672e0ab043db9e6f6f938fe54cf98acd541d6fa612a876a13a667d0c3899",
        ),
    ] {
        let original = password.clone();
        let digest = pool.derive(&password, SALT).unwrap();
        assert_eq!(*digest, unhex(expected));
        assert_eq!(password, original);
        assert_eq!(pool.usage().operations, 0);
        assert_eq!(pool.usage().workspace_bytes, 0);
    }
}

#[test]
fn public_roundtrip_randomizes_salt_and_rejects_wrong_full_password() {
    let pool = PasswordPool::new(1).unwrap();
    let password = b"synthetic\0credential";
    let first = pool.hash(password).unwrap();
    let second = pool.hash(password).unwrap();
    assert_ne!(first.encode(), second.encode());
    assert_ne!(first.salt, second.salt);
    assert!(pool.verify(password, &first).unwrap());
    assert!(pool.verify(password, &second).unwrap());
    for wrong in [
        b"synthetic".as_slice(),
        b"synthetic\0credentiaL",
        b"synthetic\0credential\0",
    ] {
        assert!(!pool.verify(wrong, &first).unwrap());
    }
    let decoded = PasswordDigest::decode(&first.encode()).unwrap();
    assert!(pool.verify(password, &decoded).unwrap());
    assert_eq!(pool.usage().operations, 0);
}

#[test]
fn passwords_are_not_truncated_or_unicode_normalized() {
    let pool = PasswordPool::new(1).unwrap();
    let mut maximum = vec![b'x'; MAX_PASSWORD_BYTES];
    let digest = pool.hash(&maximum).unwrap();
    maximum[MAX_PASSWORD_BYTES - 1] = b'y';
    assert!(!pool.verify(&maximum, &digest).unwrap());
    assert!(
        !pool
            .verify(&maximum[..MAX_PASSWORD_BYTES - 1], &digest)
            .unwrap()
    );
    let composed = pool.hash("é".as_bytes()).unwrap();
    assert!(!pool.verify("e\u{301}".as_bytes(), &composed).unwrap());
    assert!(pool.verify("é".as_bytes(), &composed).unwrap());
    let smallest = pool.hash(&[0]).unwrap();
    assert!(pool.verify(&[0], &smallest).unwrap());
    assert!(!pool.verify(&[1], &smallest).unwrap());
}

#[test]
fn malformed_inputs_are_rejected_before_admission_even_when_full() {
    let pool = PasswordPool::new(1).unwrap();
    let lease = pool.reserve().unwrap();
    let digest = PasswordDigest::from_parts(*SALT, [9; 32]);
    for password in [Vec::new(), vec![b'x'; MAX_PASSWORD_BYTES + 1]] {
        assert!(matches!(pool.hash(&password), Err(PasswordError::Input)));
        assert_eq!(pool.verify(&password, &digest), Err(PasswordError::Input));
        assert_eq!(
            pool.derive(&password, SALT).err(),
            Some(PasswordError::Input)
        );
        assert_eq!(pool.usage().operations, 1);
    }
    assert!(matches!(pool.hash(b"valid"), Err(PasswordError::Busy)));
    assert_eq!(pool.verify(b"valid", &digest), Err(PasswordError::Busy));
    drop(lease);
    assert_eq!(pool.usage().workspace_bytes, 0);
}

#[test]
fn configuration_and_admission_share_exact_bounded_counts() {
    for maximum in [0, MAX_PASSWORD_OPERATIONS + 1, usize::MAX] {
        assert!(matches!(
            PasswordPool::new(maximum),
            Err(PasswordError::Configuration)
        ));
    }
    for maximum in 1..=MAX_PASSWORD_OPERATIONS {
        let pool = PasswordPool::new(maximum).unwrap();
        let clone = pool.clone();
        assert_eq!(pool.shared.blocks, 19456);
        assert_eq!(std::mem::size_of::<Block>(), 1024);
        assert_eq!(pool.shared.hasher.params().m_cost(), PASSWORD_MEMORY_KIB);
        assert_eq!(pool.shared.hasher.params().t_cost(), PASSWORD_ITERATIONS);
        assert_eq!(pool.shared.hasher.params().p_cost(), PASSWORD_PARALLELISM);
        let mut leases = Vec::new();
        for count in 1..=maximum {
            leases.push(clone.reserve().unwrap());
            assert_eq!(
                pool.usage(),
                PasswordUsage {
                    operations: count,
                    workspace_bytes: count * PASSWORD_MEMORY_BYTES,
                }
            );
        }
        assert!(matches!(pool.reserve(), Err(PasswordError::Busy)));
        leases.pop();
        let replacement = pool.reserve().unwrap();
        drop(leases);
        assert_eq!(clone.usage().operations, 1);
        drop(replacement);
        assert_eq!(clone.usage().operations, 0);
    }
}

#[test]
fn racing_clones_never_admit_more_than_four_leases() {
    let pool = PasswordPool::new(4).unwrap();
    let start = Arc::new(Barrier::new(9));
    let held = Arc::new(Barrier::new(9));
    let release = Arc::new(Barrier::new(9));
    std::thread::scope(|scope| {
        let mut handles = Vec::new();
        for _ in 0..8 {
            let (pool, start, held, release) =
                (pool.clone(), start.clone(), held.clone(), release.clone());
            handles.push(scope.spawn(move || {
                start.wait();
                let lease = pool.reserve();
                held.wait();
                release.wait();
                lease.is_ok()
            }));
        }
        start.wait();
        held.wait();
        assert_eq!(pool.usage().operations, 4);
        assert_eq!(pool.usage().workspace_bytes, 4 * PASSWORD_MEMORY_BYTES);
        release.wait();
        let successes = handles
            .into_iter()
            .map(|h| usize::from(h.join().unwrap()))
            .sum::<usize>();
        assert_eq!(successes, 4);
    });
    assert_eq!(pool.usage().operations, 0);
}

#[test]
fn live_workspaces_hold_slots_and_zeroizing_blocks_can_be_wiped() {
    let pool = PasswordPool::new(2).unwrap();
    let mut first = pool.workspace().unwrap();
    let second = pool.clone().workspace().unwrap();
    assert_eq!(first.blocks.len(), pool.shared.blocks);
    assert_eq!(first.blocks.capacity(), pool.shared.blocks);
    assert_eq!(pool.usage().workspace_bytes, 2 * PASSWORD_MEMORY_BYTES);
    assert!(matches!(pool.workspace(), Err(PasswordError::Busy)));
    first.blocks[0].as_mut().fill(0x5a);
    first.blocks[19455].as_mut().fill(0xa5);
    // Observe the documented wipe before deallocation; never inspect freed memory.
    for block in first.blocks.iter_mut() {
        block.zeroize();
    }
    assert!(
        first
            .blocks
            .iter()
            .all(|b| b.as_ref().iter().all(|v| *v == 0))
    );
    assert_eq!(pool.usage().operations, 2);
    drop(first);
    assert_eq!(pool.usage().operations, 1);
    drop(second);
    assert_eq!(pool.usage().workspace_bytes, 0);
}

#[test]
fn concurrent_real_hashes_use_shared_hasher_without_changing_parameters() {
    let pool = PasswordPool::new(4).unwrap();
    std::thread::scope(|scope| {
        let handles: Vec<_> = (0..4)
            .map(|_| {
                let pool = pool.clone();
                scope.spawn(move || *pool.derive(b"synthetic-password", SALT).unwrap())
            })
            .collect();
        for handle in handles {
            assert_eq!(
                handle.join().unwrap(),
                unhex("a4ae807f135c26201d1689dd0d26d93d04e28a91bf16dd1f3381535303db8656")
            );
        }
    });
    assert_eq!(pool.usage().operations, 0);
}

#[test]
fn held_concurrent_workspaces_refuse_extra_memory_until_all_owners_drop() {
    let pool = PasswordPool::new(4).unwrap();
    let held = Arc::new(Barrier::new(5));
    let release = Arc::new(Barrier::new(5));
    std::thread::scope(|scope| {
        for _ in 0..4 {
            let (pool, held, release) = (pool.clone(), held.clone(), release.clone());
            scope.spawn(move || {
                let workspace = pool.workspace().unwrap();
                held.wait();
                release.wait();
                drop(workspace);
            });
        }
        held.wait();
        assert_eq!(pool.usage().workspace_bytes, 4 * PASSWORD_MEMORY_BYTES);
        assert!(matches!(pool.workspace(), Err(PasswordError::Busy)));
        assert!(matches!(pool.hash(b"valid"), Err(PasswordError::Busy)));
        release.wait();
    });
    assert_eq!(pool.usage().operations, 0);
    drop(pool.workspace().unwrap());
    assert_eq!(pool.usage().workspace_bytes, 0);
}

#[test]
fn workspace_unwinding_returns_the_slot_to_surviving_clones() {
    let pool = PasswordPool::new(1).unwrap();
    let clone = pool.clone();
    let result = std::panic::catch_unwind(|| {
        let mut workspace = clone.workspace().unwrap();
        workspace.blocks[0].as_mut().fill(42);
        assert_eq!(pool.usage().operations, 1);
        // An internal test fault, never induced by parser/password input.
        panic!("synthetic internal unwind");
    });
    assert!(result.is_err());
    assert_eq!(pool.usage().workspace_bytes, 0);
    drop(pool.workspace().unwrap());
}

#[test]
fn opaque_payload_tampering_is_not_an_integrity_check_but_cannot_verify() {
    let pool = PasswordPool::new(1).unwrap();
    let record = pool.hash(b"synthetic-password").unwrap().encode();
    for position in [24, 39, 40, 71] {
        let mut changed = record;
        changed[position] ^= 1;
        let decoded = PasswordDigest::decode(&changed).unwrap();
        assert_eq!(decoded.encode(), changed);
        assert!(!pool.verify(b"synthetic-password", &decoded).unwrap());
    }
    assert_eq!(pool.usage().operations, 0);
}

fn canonical() -> [u8; PASSWORD_RECORD_BYTES] {
    PasswordDigest::from_parts(*SALT, [0x5a; 32]).encode()
}

#[test]
fn record_layout_is_fixed_and_all_header_mutations_fail_closed() {
    let encoded = canonical();
    assert_eq!(&encoded[..8], b"EBPWD\0\0\0");
    assert_eq!(&encoded[8..12], &[1, 0, 2, 0x13]);
    assert_eq!(&encoded[12..16], &19456_u32.to_le_bytes());
    assert_eq!(&encoded[16..20], &2_u32.to_le_bytes());
    assert_eq!(&encoded[20..24], &1_u32.to_le_bytes());
    assert_eq!(&encoded[24..40], SALT);
    assert_eq!(&encoded[40..], &[0x5a; 32]);
    for length in 0..PASSWORD_RECORD_BYTES {
        assert!(matches!(
            PasswordDigest::decode(&encoded[..length]),
            Err(PasswordError::Record)
        ));
    }
    let mut trailing = encoded.to_vec();
    trailing.push(0);
    assert!(matches!(
        PasswordDigest::decode(&trailing),
        Err(PasswordError::Record)
    ));
    for byte in 0..24 {
        for bit in 0..8 {
            let mut mutated = encoded;
            mutated[byte] ^= 1 << bit;
            assert!(PasswordDigest::decode(&mutated).is_err());
        }
    }
    for version in [0_u16, 2, 255, 256, u16::MAX] {
        let mut mutated = encoded;
        mutated[8..10].copy_from_slice(&version.to_le_bytes());
        assert!(
            matches!(PasswordDigest::decode(&mutated), Err(PasswordError::Version(v)) if v == version)
        );
    }
}

#[test]
fn secrets_are_absent_from_debug_and_input_errors() {
    let digest = PasswordDigest::from_parts(*SALT, [0x5a; 32]);
    assert_eq!(format!("{digest:?}"), "PasswordDigest(redacted)");
    assert_eq!(format!("{:?}", digest.clone()), "PasswordDigest(redacted)");
    for error in [
        PasswordError::Input,
        PasswordError::Record,
        PasswordError::Policy,
        PasswordError::Busy,
        PasswordError::Allocation,
        PasswordError::Hashing,
        PasswordError::Randomness,
    ] {
        assert!(!error.to_string().contains("0123456789abcdef"));
        assert!(!format!("{error:?}").contains("synthetic-password"));
    }
    assert!(!format!("{:?}", PasswordPool::new(1).unwrap()).contains("argon2"));
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(512))]
    #[test]
    fn arbitrary_records_only_pass_exact_fixed_policy(bytes in prop::collection::vec(any::<u8>(), 0..257)) {
        let header = canonical();
        let expected = bytes.len() == 72 && bytes[..24] == header[..24];
        let decoded = PasswordDigest::decode(&bytes);
        prop_assert_eq!(decoded.is_ok(), expected);
        if let Ok(decoded) = decoded {
            let encoded = decoded.encode();
            prop_assert_eq!(encoded.as_slice(), bytes.as_slice());
        }
    }
    #[test]
    fn salt_and_digest_are_opaque_payload_not_user_selected_costs(salt in any::<[u8;16]>(), hash in any::<[u8;32]>()) {
        let encoded = PasswordDigest::from_parts(salt, hash).encode();
        let decoded = PasswordDigest::decode(&encoded).unwrap();
        prop_assert_eq!(decoded.encode(), encoded);
    }
    #[test]
    fn arbitrary_costs_never_reach_hashing(m in any::<u32>(), t in any::<u32>(), p in any::<u32>()) {
        let mut encoded = canonical();
        encoded[12..16].copy_from_slice(&m.to_le_bytes());
        encoded[16..20].copy_from_slice(&t.to_le_bytes());
        encoded[20..24].copy_from_slice(&p.to_le_bytes());
        prop_assert_eq!(PasswordDigest::decode(&encoded).is_ok(), m == 19456 && t == 2 && p == 1);
    }
    #[test]
    fn generated_lease_lifetimes_follow_an_independent_count_model(
        maximum in 1_usize..=4, operations in prop::collection::vec(any::<u8>(), 0..256)
    ) {
        let pool = PasswordPool::new(maximum).unwrap();
        let clone = pool.clone();
        let mut owners = Vec::new();
        for operation in operations {
            match operation % 3 {
                0 => {
                    let admitted = clone.reserve();
                    prop_assert_eq!(admitted.is_ok(), owners.len() < maximum);
                    if let Ok(owner) = admitted { owners.push(owner); }
                }
                1 => { owners.pop(); }
                _ => { owners.clear(); }
            }
            prop_assert_eq!(pool.usage().operations, owners.len());
            prop_assert_eq!(clone.usage().workspace_bytes, owners.len() * PASSWORD_MEMORY_BYTES);
        }
        drop(owners);
        prop_assert_eq!(pool.usage().operations, 0);
    }
}
