use emilybase_index::{BPlusTree, INDEX_VERSION, Key, RecordPointer};
use sha2::{Digest, Sha256};

// Frozen from the published d75751b implementation, not generated by this test.
const EMPTY: &str = "ce86012eeb017d10f5952a72f0017a27dfc6f42dd53b1c865ea52561a458003e";
const SPLITS: &str = "9dc3f7b58846fdbcea15897ce91cf6e429ab7bfa10db902aeb4b85c0e53fe0d4";
const UNICODE: &str = "9640cb57e9898e18137dd28af6511b4ff0728e05cdccd8a7e037baac860fdb3c";

fn frozen_digest(tree: &BPlusTree) -> String {
    let images = tree.page_images().unwrap();
    let mut digest = Sha256::new();
    digest.update(tree.root_id().to_le_bytes());
    digest.update((images.len() as u32).to_le_bytes());
    for image in images {
        assert_eq!(u16::from_le_bytes([image[4], image[5]]), INDEX_VERSION);
        digest.update(image);
    }
    format!("{:x}", digest.finalize())
}

fn reopen(tree: &BPlusTree) -> BPlusTree {
    let restored = BPlusTree::from_pages(tree.root_id(), &tree.page_images().unwrap()).unwrap();
    assert_eq!(&restored, tree);
    restored
}

#[test]
fn published_version_one_images_remain_byte_identical_and_mutable() {
    let empty = BPlusTree::new();
    assert_eq!(frozen_digest(&empty), EMPTY);
    assert_eq!(reopen(&empty), empty);

    let mut splits = BPlusTree::new();
    for key in (0..256i64).rev() {
        splits
            .insert(
                Key::Integer(key),
                RecordPointer {
                    page_id: key as u64 + 1,
                    slot_id: key as u16,
                },
            )
            .unwrap();
    }
    assert_eq!((splits.root_id(), splits.page_count()), (19, 37));
    assert_eq!(frozen_digest(&splits), SPLITS);
    let mut restored = reopen(&splits);
    let replacement = RecordPointer {
        page_id: u64::MAX,
        slot_id: u16::MAX,
    };
    restored.replace(&Key::Integer(255), replacement).unwrap();
    for key in 0..255 {
        restored.remove(&Key::Integer(key)).unwrap();
    }
    assert_eq!(restored.len(), 1);
    assert_eq!(
        reopen(&restored).get(&Key::Integer(255)).unwrap(),
        Some(replacement)
    );
    assert_eq!(frozen_digest(&splits), SPLITS);

    let mut unicode = BPlusTree::new();
    let keys = [
        Key::Integer(i64::MIN),
        Key::Integer(i64::MAX),
        Key::Text(String::new()),
        Key::Text("é".into()),
        Key::Text("é".into()),
        Key::Text("я".into()),
        Key::Text("🌌".into()),
    ];
    for (i, key) in keys.into_iter().enumerate() {
        unicode
            .insert(
                key,
                RecordPointer {
                    page_id: i as u64 + 1,
                    slot_id: i as u16,
                },
            )
            .unwrap();
    }
    assert_eq!(frozen_digest(&unicode), UNICODE);
    let mut restored = reopen(&unicode);
    assert_ne!(
        restored.remove(&Key::Text("é".into())).unwrap(),
        restored.remove(&Key::Text("é".into())).unwrap()
    );
    assert_eq!(restored.validate().unwrap(), 5);
    reopen(&restored);
}
