[package]
name = "emilybase-object-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
crc32fast = "1.5"
sha2 = "0.10"
thiserror = "2"
rustix = { version = "1", features = ["fs"] }
emilybase-storage = { path = "../storage" }

[dev-dependencies]
proptest = "1"
tempfile = "3"

[lints]
workspace = true
