[package]
name = "emilybase-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
crc32fast = "1.5"
thiserror = "2"
getrandom = "0.3"
rustix = { version = "1", features = ["fs"] }

[dev-dependencies]
proptest = "1"
tempfile = "3"

[lints]
workspace = true
