[package]
name = "emilybase-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "emilybase"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
emilybase-storage = { path = "../storage" }

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
