[package]
name = "emilybase-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "emilybase"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
emilybase-storage = { path = "../storage" }
emilybase-catalog = { path = "../catalog" }
emilybase-database = { path = "../database" }
emilybase-transactions = { path = "../transactions" }
emilybase-backup = { path = "../backup" }
emilybase-query = { path = "../query" }
emilybase-index = { path = "../index" }
emilybase-server = { path = "../server" }
serde = "1"
serde_json = "1"

[dev-dependencies]
emilybase-auth = { path = "../auth" }
tempfile = "3"

[lints]
workspace = true
