[package]
name = "emilybase-query"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
emilybase-catalog = { path = "../catalog" }
emilybase-database = { path = "../database" }
emilybase-transactions = { path = "../transactions" }
serde = { version = "1", features = ["derive"] }
thiserror = "2"

[dev-dependencies]
proptest = "1"
tempfile = "3"

[lints]
workspace = true
