[package]
name = "emilybase-query"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
emilybase-catalog = { path = "../catalog" }
thiserror = "2"

[dev-dependencies]
proptest = "1"

[lints]
workspace = true
