[package]
name = "emilybase-transactions"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
emilybase-storage = { path = "../storage" }
emilybase-catalog = { path = "../catalog" }
emilybase-database = { path = "../database" }
emilybase-wal = { path = "../wal" }
getrandom = "0.3"
thiserror = "2"

[dev-dependencies]
tempfile = "3"
proptest = "1"

[lints]
workspace = true
